# Generated by Django 5.1.1 on 2025-05-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_core', '0003_farmerprofile_queryhistory_delete_webhookmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('daily_stats', models.JSONField()),
                ('weekly_stats', models.JSONField()),
                ('weekly_plan', models.JSONField()),
                ('advice', models.TextField()),
            ],
        ),
    ]
